"""LAMMPS in-file writer with the streaming (gravity) NEMD template.

Template highlights (see the research manual):
  - thermostat on y/z only, excluding the flow direction x
  - ``fix addforce`` streaming drive along +x
  - rigid water via SHAKE, membranes fixed with ``fix setforce``
  - PPPM electrostatics with geometric mixing
"""

from __future__ import annotations

from pathlib import Path

from nanomd.core.forcefields.library import WALL_ATOM_NAMES, all_atom_types
from nanomd.core.models.structure import Structure
from nanomd.core.models.system import System


def write_input_file(
    system: System,
    structure: Structure,
    data_filename: str,
    path: str | Path,
    production_steps: int = 50000,
) -> Path:
    """Write the LAMMPS in file and return the output path."""
    path = Path(path)
    types = structure.type_names()
    type_id = {name: i + 1 for i, name in enumerate(types)}
    library = all_atom_types(prefer_water=system.water.model_key)

    pair_lines = [
        f"pair_coeff {type_id[name]} {type_id[name]} "
        f"{library[name].epsilon:.4f} {library[name].sigma:.4f}"
        for name in types
    ]
    # Membrane carbons plus grafted functional-group atoms belong to the wall
    # group; a plain prefix check would wrongly match "Cl-".
    wall_type_ids = [type_id[name] for name in types if name in WALL_ATOM_NAMES]
    wall_types = " ".join(map(str, wall_type_ids)) if wall_type_ids else "1"

    text = f"""# {system.name} — generated by NanoMD Designer

units        real
atom_style   full
boundary     p p f

read_data    {data_filename}

pair_style   lj/cut/coul/long 10.0
pair_modify  mix geometric
kspace_style pppm 1e-4
special_bonds lj 0.0 0.0 0.0 coul 0.0 0.0 0.0

# --- pair coefficients (OPLS-AA / TIP3P, real units) ---
{chr(10).join(pair_lines)}

bond_style   zero
angle_style  zero

# --- groups ---
group        wall type {wall_types}
group        fluid subtract all wall

# --- membranes are rigid ---
velocity     wall set 0.0 0.0 0.0
fix          fixwall wall setforce 0.0 0.0 0.0

# --- rigid water ---
fix          shake fluid shake 1e-4 100 0 0 1 1

# --- thermostat on y/z only (exclude flow direction x) ---
compute      tpartial fluid temp/partial 0 1 1
fix          nvt fluid nvt temp {system.temperature_k:.1f} {system.temperature_k:.1f} 100.0
fix_modify   nvt temp tpartial

# --- streaming drive along +x (gravity method) ---
fix          drive fluid addforce {system.drive_force_kcal_mol_ang:.6f} 0.0 0.0

thermo       100
thermo_style custom step temp press pe ke
thermo_modify flush yes

# --- equilibration ---
minimize     1e-6 1e-8 1000 10000
run          1000

# --- production ---
reset_timestep 0
dump         traj all custom 1000 dump.lammpstrj id type x y z vx vy vz
run          {production_steps}
"""
    path.write_text(text, encoding="utf-8")
    return path
